(TeX-add-style-hook
 "lib"
 (lambda ()
   (LaTeX-add-bibitems
    "fuzzi_moss_repo"
    "pydysofu_repo"
    "asp_repo"
    "theatre_repo"
    "process_mining_research_agenda"
    "secsy"
    "on_bp_variant_generation"
    "threegoodreasons"
    "mattia_sts"
    "pdsf_paper"
    "log_noise_removal"
    "thesis_process_structure_trees"
    "wfgraphs_repo"
    "van3536bpi"
    "bpi_model_repo"
    "hanakawa"
    "degraded_modes"
    "reference_agile_model"
    "marsh_thesis"
    "qpq_game"
    "endlessh"
    "pdsf_repo"
    "bazoun2014business"
    "dori1995object"
    "iso_pnml"
    "aalst_generating_logs"
    "xl1"))
 :bibtex)

