#+author: Tom Wallis
#+date: 12/12/17

* What I did in my autumn

I've been researching a few things:
+ Holons and System Composition
  - There doesn't seem to be a ton of work on composing really big things and having that validated
  - Decomposing is hard too
  - We've got things like resp modelling and composition via things like bigraphs, but none of them seem /good/.
  - Interesting to think about how systems compose particularly for things like dataflows
    - If we're developing a large system, and composing two different systems together, the ways that the two subsystems can talk might be very complex.
    - How do you make sure you're modelling all of the different communications?
  - When we're /architecting/ or /refactoring/ a system, can we engineer its properties?
+ Processes
  - How does a system change?
  - What can we determine about something like a business process? About system processes writ large?
  - A large system might change in a number of ways and in a number of places.
+ How do big things get modelled?
  - Tradeoff between detail and rigour at a large scale
    - We want both!
  - I think Obashi's unusually good at both, but a large part of this is scope (focus on dataflows particularly) and tooling (tooling is usually very poor!)
  - I want to find good ways to break this tradeoff
+ Bigraphs
  - I can encode Obashi in them!
  - I think this could be quite interesting with bigraphical reactive systems for modelling....
  - They have some issues but I think I can solve them
    - Metric spaces
    - Sharing
  - More work to do
